theme: minima
#remote_theme: jekyll/minima

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Site settings
#    Used to personalize the site. If you look in the HTML files,
#    you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#    You can create any custom variable you like, and they will be accessible
#    in the templates via {{ site.myvariable }} for example.
url: "https://elementsproject.org" 
baseurl: "" # the subpath of your site if neded, e.g. /sitecontent

#email: elements@blockstream.io

title: elementsproject.org
description: >- # this means to ignore newlines
  Elements - an open source, sidechain-capable blockchain platform.

plugins:
  - jekyll-redirect-from

web_github_link: https://github.com/ElementsProject/elementsproject.github.io
elements_github_link: https://github.com/ElementsProject/elements
slack_link: https://bitcoincore.slack.com
slack_sign_up_link: https://bitcoincoreslack.herokuapp.com
mailing_list_link: https://lists.linuxfoundation.org/mailman/listinfo/sidechains-dev
freenode_irc_link: https://webchat.freenode.net/?channels=%23sidechains-dev

collections:
  doc:
    output: true

exclude:
  - _config.yml
  - LICENSE
  - README.md
  - vendor  # Travis CI creates a vendor/ dir with files we shouldn't render
  - contrib
